# This is a TOML document.

title = "Morning Files Toml"

[owner]
name = "Mahmoud"
organization = "NCB"

[user]
 name = "p040747"
 
[logs]
 location = "logs//"
 name = "morning-log.txt"
 flag = 1 #os.O_WRONLY
 permission = 0666

[hotkey]
 command = "RSATokenAutomation.ahk"
 location = "C:\\Users\\masterserver\\Desktop\\master-files-automation\\hotkey\\"
 outputlocation = "C:\\Users\\masterserver\\Desktop\\master-files-automation\\hotkey\\token.ini"

[winscp]
  location = "C:\\Users\\masterserver\\Desktop\\master-files-automation\\winscp\\"
  proxy = "mitproxy"
  outputlocation = "C:\\Users\\masterserver\\Desktop\\master-files-automation\\winscp\\out\\"
  command = "winscp.bat"
  transfile = "transfer.txt"
  log = "morning-log.txt"
  logloc = "C:\\Users\\masterserver\\Desktop\\master-files-automation\\winscp\\logs\\"

  
[servers]
 # You can indent as you please. Tabs or spaces. TOML don't care.
  [servers.prod]
  url = "prod.mfe.mastercard.com"
  ip = "12.22.155.207"
  port= "15022"

  [servers.uprod]
  url = "uprod.mfe.mastercard.com"
  ip = "12.22.155.208"
  port= "16022"

  [servers.test]
  url = "mtf.mfe.mastercard.com"
  ip = "216.119.219.6"
  port= "15022"
  
  [servers.utest]
  url = "umtf.mfe.mastercard.com"
  ip = "216.119.219.7"
  port= "16022"

[files]
# You can indent as you please. Tabs or spaces. TOML don't care.
  [files.T632]
  serverlocation = "/0071969/production/download/T632"
  servername = "MCI.AR.T632.M.E0071969.D*"
  get = true
  outputname = "TT632T0"
  outputlocation = "C:\\MCONLINE\\MFE\\DOWNLOAD\\632\\"
  prefix = "*.632"
  
  [files.TSI0]
  serverlocation = "/0071969/production/download/TSI0"
  servername = "MCI.AR.TSI0.M.E0071969.D*"
  get = true
  outputname = "TTSI0T0"
  outputlocation = "C:\\MCONLINE\\MFE\\DOWNLOAD\\"
  prefix = "*.TSI"
  
  [files.T067]
  serverlocation = "/0071969/production/download/T067"
  servername = "MCI.AR.T067.B.CCAR1212.D*"
  get = true
  outputname = "TT067T0"
  outputlocation = "C:\\MCONLINE\\MFE\\DOWNLOAD\\"
  prefix = "*.067"